// The songs: traditional tunes (all public domain), the chord progressions of
// a few well-known songs, and the loops most pop songs are built on.
//
// Each song is {name, kind, group, key, beats, tip, bars}. group is one of
// 'song' | 'pop' | 'loop'. bars is a list of [chordSymbol, cue] pairs, one
// per bar; the symbol must parse with parseChord() in theory.js.
//
// Well-known songs carry chord progressions only. Their lyrics are still in
// copyright, unlike the traditionals, so their cues mark sections instead of
// words.

export const SONGS = [
  // ---------- easy songs (all public domain) ----------
  {
    name: 'Row Your Boat',
    kind: 'traditional',
    group: 'song',
    key: 'C major',
    beats: 4,
    tip: 'The easiest one here \u2014 almost the whole song is a single chord, so you can spend the time getting both hands landing together.',
    bars: [
      ['C', 'Row, row, row your boat'],
      ['C', 'gent-ly down the stream'],
      ['C', 'mer-ri-ly, mer-ri-ly,'],
      ['C', 'mer-ri-ly, mer-ri-ly,'],
      ['G', 'life is but a'],
      ['C', 'dream'],
    ],
  },

  {
    name: 'Twinkle, Twinkle',
    kind: 'traditional',
    group: 'song',
    key: 'C major',
    beats: 4,
    tip: 'Three chords for the whole tune. Play both hands together on beat 1 and let the chord ring for the rest of the bar.',
    bars: [
      ['C', 'Twin-kle twin-kle'],
      ['C', 'lit-tle star'],
      ['F', 'how I won-der'],
      ['C', 'what you are'],
      ['F', 'Up a-bove the'],
      ['C', 'world so high'],
      ['G', 'like a dia-mond'],
      ['C', 'in the sky'],
    ],
  },

  {
    name: 'Ode to Joy',
    kind: 'Beethoven',
    group: 'song',
    key: 'C major',
    beats: 4,
    tip: 'Only two chords the whole way through. The cues are the melody notes \u2014 play them with your right hand once the chords feel easy.',
    bars: [
      ['C', '\u266a E E F G'],
      ['G', '\u266a G F E D'],
      ['C', '\u266a C C D E'],
      ['G', '\u266a E D D'],
      ['C', '\u266a E E F G'],
      ['G', '\u266a G F E D'],
      ['C', '\u266a C C D E'],
      ['C', '\u266a D C C'],
    ],
  },

  {
    name: 'When the Saints',
    kind: 'traditional',
    group: 'song',
    key: 'C major',
    beats: 4,
    tip: 'Bright and marching. Sit on C for four bars, then the F in bar 5 is the lift everyone waits for.',
    bars: [
      ['C', 'Oh, when the saints'],
      ['C', 'go march-ing in'],
      ['C', 'oh, when the saints go'],
      ['C', 'march-ing in'],
      ['F', 'Oh Lord, I want to be'],
      ['C', 'in that num-ber'],
      ['G', 'when the saints go'],
      ['C', 'march-ing in'],
    ],
  },

  {
    name: 'Amazing Grace',
    kind: 'traditional',
    group: 'song',
    key: 'G major',
    beats: 3,
    tip: 'Three beats to a bar, so count 1-2-3. A gentle one: the left hand can play on beat 1 only.',
    bars: [
      ['G', 'A-ma-zing'],
      ['G', 'grace, how'],
      ['C', 'sweet the'],
      ['G', 'sound'],
      ['G', 'that saved a'],
      ['G', 'wretch like'],
      ['D', 'me'],
      ['D', ''],
      ['G', 'I once was'],
      ['G', 'lost, but'],
      ['C', 'now am'],
      ['G', 'found'],
      ['G', 'was blind but'],
      ['D', 'now I'],
      ['G', 'see'],
      ['G', ''],
    ],
  },

  {
    name: 'Auld Lang Syne',
    kind: 'traditional',
    group: 'song',
    key: 'G major',
    beats: 4,
    tip: 'The New Year tune. Only four different chords, and the hands barely move between them.',
    bars: [
      ['G', 'Should auld ac-'],
      ['C', 'quain-tance be for-'],
      ['G', 'got'],
      ['D', 'and'],
      ['G', 'ne-ver brought to'],
      ['C', 'mind, should auld ac-'],
      ['D', 'quain-tance be for-'],
      ['G', 'got'],
    ],
  },

  {
    name: 'House of the Rising Sun',
    kind: 'traditional',
    group: 'song',
    key: 'A minor',
    beats: 4,
    tip: 'A minor-key folk classic. Four bars up, four bars back \u2014 repeat the whole thing as many times as you like.',
    bars: [
      ['Am', 'There is a'],
      ['C', 'house in'],
      ['D', 'New Or-'],
      ['F', 'leans'],
      ['Am', 'they call the'],
      ['C', 'Ri-sing'],
      ['E', 'Sun'],
      ['E', ''],
    ],
  },

  // ---------- well-known songs ----------
  // Chord progressions only. These lyrics are still in copyright, unlike the
  // traditionals above, so the cues mark sections instead of words.
  {
    name: 'Let It Be',
    kind: 'The Beatles',
    group: 'pop',
    key: 'C major',
    beats: 4,
    tip: 'The four-chord song. It is the pop loop with a different ending \u2014 bars 7 and 8 walk F down to C instead of hanging on F.',
    bars: [
      ['C', 'verse'],
      ['G', ''],
      ['Am', ''],
      ['F', ''],
      ['C', ''],
      ['G', ''],
      ['F', 'coming home'],
      ['C', ''],
    ],
  },

  {
    name: 'Knockin\u2019 on Heaven\u2019s Door',
    kind: 'Bob Dylan',
    group: 'pop',
    key: 'G major',
    beats: 4,
    tip: 'Two bars each, three chords, and the only change is Am in the first half becoming C in the second. About as easy as a famous song gets.',
    bars: [
      ['G', 'first half'],
      ['D', ''],
      ['Am', ''],
      ['Am', ''],
      ['G', 'second half'],
      ['D', ''],
      ['C', ''],
      ['C', ''],
    ],
  },

  {
    name: 'Stand By Me',
    kind: 'Ben E. King',
    group: 'pop',
    key: 'C major',
    beats: 4,
    tip: 'The doo-wop loop with a name on it. Play it slow and let the left hand walk \u2014 that bass line is the whole song.',
    bars: [
      ['C', ''],
      ['C', ''],
      ['Am', ''],
      ['Am', ''],
      ['F', ''],
      ['G', ''],
      ['C', ''],
      ['C', ''],
    ],
  },

  {
    name: 'Hallelujah',
    kind: 'Leonard Cohen',
    group: 'pop',
    key: 'C major',
    beats: 4,
    tip: 'The verse literally describes itself: bar 5 is the fourth (F), bar 6 is the fifth (G), and the minor fall and major lift follow.',
    bars: [
      ['C', 'verse'],
      ['Am', ''],
      ['C', ''],
      ['Am', ''],
      ['F', 'the fourth'],
      ['G', 'the fifth'],
      ['C', ''],
      ['G', ''],
    ],
  },

  {
    name: 'Country Roads',
    kind: 'John Denver',
    group: 'pop',
    key: 'G major',
    beats: 4,
    tip: 'Bright and easy, and the Em in bar 2 is the only shade in it. Good one to sing along with once your hands know the shapes.',
    bars: [
      ['G', 'verse'],
      ['Em', ''],
      ['D', ''],
      ['C', ''],
      ['G', ''],
      ['Em', ''],
      ['D', ''],
      ['G', ''],
    ],
  },

  {
    name: 'Zombie',
    kind: 'The Cranberries',
    group: 'pop',
    key: 'E minor',
    beats: 4,
    tip: 'Four bars, round and round, the entire song. Darker than the rest of this list \u2014 it starts on the minor and never fully resolves.',
    bars: [
      ['Em', ''],
      ['C', ''],
      ['G', ''],
      ['D', ''],
    ],
  },

  {
    name: '\u017Divot je jen n\u00E1hoda',
    kind: 'Je\u017Eek \u2013 DRAFT, check by ear',
    group: 'pop',
    key: 'C major',
    beats: 4,
    tip: '\u26A0 Draft chart, not verified \u2014 press play song and tell me which bars are wrong. It is a 1932 Je\u017Eek swing tune, so it leans on sevenths and the ii\u2013V turnaround (Dm\u2013G7) rather than plain triads. Bar 12\u2019s Fm is the minor-four, very much of the period. Je\u017Eek died in 1942 so the music is public domain; the Voskovec and Werich words are not, hence no lyrics.',
    bars: [
      ['C', 'A section'],
      ['A7', ''],
      ['Dm', ''],
      ['G7', ''],
      ['C', ''],
      ['A7', ''],
      ['Dm', ''],
      ['G7', ''],
      ['C', 'B section'],
      ['C7', ''],
      ['F', ''],
      ['Fm', 'minor four'],
      ['C', ''],
      ['A7', ''],
      ['G7', ''],
      ['C', ''],
    ],
  },

  // ---------- progressions to loop ----------
  {
    name: 'Sunshine',
    kind: 'I - IV - V',
    group: 'loop',
    key: 'C major',
    beats: 4,
    tip: 'The three happiest chords in music. Folk, country and early rock nearly all live here \u2014 loop it and it just sounds glad.',
    bars: [
      ['C', ''],
      ['F', ''],
      ['G', ''],
      ['C', ''],
    ],
  },

  {
    name: 'Campfire',
    kind: 'I - IV - I - V',
    group: 'loop',
    key: 'C major',
    beats: 4,
    tip: 'Bounces home to C between every change, which makes it the easiest loop to sing anything over.',
    bars: [
      ['C', ''],
      ['F', ''],
      ['C', ''],
      ['G', ''],
    ],
  },

  {
    name: 'Anthem',
    kind: 'I - V - IV',
    group: 'loop',
    key: 'C major',
    beats: 4,
    tip: 'Big and wide open \u2014 the stadium-chorus shape. Try it with the octave bass and the steady tempo.',
    bars: [
      ['C', ''],
      ['G', ''],
      ['F', ''],
      ['F', ''],
    ],
  },

  {
    name: 'Bright lift',
    kind: 'I - iii - IV - V',
    group: 'loop',
    key: 'C major',
    beats: 4,
    tip: 'Every chord is a step up from the one before, so it feels like it keeps climbing without ever arriving.',
    bars: [
      ['C', ''],
      ['Em', ''],
      ['F', ''],
      ['G', ''],
    ],
  },

  {
    name: 'Pop loop',
    kind: 'I - V - vi - IV',
    group: 'loop',
    key: 'C major',
    beats: 4,
    tip: 'The four chords behind an enormous number of pop songs. Loop it and sing anything over the top.',
    bars: [
      ['C', ''],
      ['G', ''],
      ['Am', ''],
      ['F', ''],
    ],
  },

  {
    name: 'Warm turnaround',
    kind: 'I - vi - ii - V',
    group: 'loop',
    key: 'C major',
    beats: 4,
    tip: 'The soul and jazz standard. Every chord leans into the next one and it lands back on C, so it loops forever.',
    bars: [
      ['C', ''],
      ['Am', ''],
      ['Dm', ''],
      ['G', ''],
    ],
  },

  {
    name: 'Doo-wop',
    kind: 'I - vi - IV - V',
    group: 'loop',
    key: 'C major',
    beats: 4,
    tip: 'The 1950s ballad loop. Sweet and slow \u2014 try the slow tempo.',
    bars: [
      ['C', ''],
      ['Am', ''],
      ['F', ''],
      ['G', ''],
    ],
  },

  {
    name: '12-bar blues',
    kind: 'blues in C',
    group: 'loop',
    key: 'C major',
    beats: 4,
    tip: 'The backbone of blues and early rock. Three chords, twelve bars, round and round.',
    bars: [
      ['C', ''],
      ['C', ''],
      ['C', ''],
      ['C', ''],
      ['F', ''],
      ['F', ''],
      ['C', ''],
      ['C', ''],
      ['G', ''],
      ['F', ''],
      ['C', ''],
      ['G', 'turnaround'],
    ],
  },

  {
    name: 'Canon',
    kind: 'Pachelbel, simplified',
    group: 'loop',
    key: 'C major',
    beats: 4,
    tip: 'Pachelbel\u2019s descending bass line. The left hand walks down step by step \u2014 listen for it.',
    bars: [
      ['C', ''],
      ['G', ''],
      ['Am', ''],
      ['Em', ''],
      ['F', ''],
      ['C', ''],
      ['F', ''],
      ['G', ''],
    ],
  },
];
